title: offline.mall::lang.price_category_settings.label
modelClass: OFFLINE\Mall\Models\PriceCategory
list: $/offline/mall/models/pricecategory/columns.yaml
recordUrl: 'offline/mall/pricecategories/update/:id'
noRecordsMessage: 'backend::lang.list.no_records'
recordsPerPage: 20
showSetup: true
showCheckboxes: true
defaultSort:
    column: sort_order
    direction: asc
toolbar:
    buttons: list_toolbar
    search:
        prompt: 'backend::lang.list.search_prompt'
structure:
    showTree: false
    showReorder: true
    showSorting: true
    maxDepth: 1