name: offline.mall::lang.price_category_settings.label
modelClass: OFFLINE\Mall\Models\PriceCategory
form: $/offline/mall/models/pricecategory/fields.yaml
defaultRedirect: offline/mall/pricecategories
create:
    title: offline.mall::lang.titles.price_categories.create
    redirect: 'offline/mall/pricecategories/update/:id'
    redirectClose: offline/mall/pricecategories
update:
    title: offline.mall::lang.titles.price_categories.update
    redirect: offline/mall/pricecategories
    redirectClose: offline/mall/pricecategories
preview: {  }
