<template>
    <label :for="props.id" class="field-checkbox" :class="props.invalid ? 'is-invalid' : ''">
        <input class="checkbox-input"
            type="checkbox"
            :id="props.id"
            :name="props.name"
            :disabled="props.disabled" 
            :required="props.required"
            v-model="value" />
        <div class="checkbox-label">
            <span v-if="props.label">{{ props.label }}</span>
        </div>
    </label>
</template>

<script lang="ts">
export interface CheckboxFieldProps {
    /**
     * The desired label shown next to the checkbox input element itself.
     */
    label?: string;

    /**
     * A unique field id, may already be generated by the parent FormControl component.
     */
    id?: string;

    /**
     * The desired field value, accepts boolean states only. Don't pass `yes` / `no` or similar 
     * boolish values.
     */
    modelValue?: boolean|null;

    /**
     * The desired field name.
     */
    name?: string;

    /**
     * The field disabled state.
     */
    disabled?: boolean;

    /**
     * The field required state.
     */
    required?: boolean;

    /**
     * The field invalid state.
     */
    invalid?: boolean;
}

export interface CheckboxFieldEmits {
    
    /**
     * Update model value handler.
     */
    (ev: 'update:modelValue', value: boolean|null): void;

}
</script>

<script lang="ts" setup>
import { computed } from 'vue';

// Define Component
const props = defineProps<CheckboxFieldProps>();
const emits = defineEmits<CheckboxFieldEmits>();

// States
const value = computed({
    get() {
        return props.modelValue;
    },
    set(value) {
        emits('update:modelValue', value as boolean | null);
    }
});
</script>

<style scoped>
.field-checkbox {
    @apply inline-flex;
}

.checkbox-input {
    @apply hidden;
}

.checkbox-input ~ .checkbox-label {
    @apply flex items-center relative text-xs font-semibold gap-1.5;
    @apply duration-300 ease-in-out;
    transition-property: background-color, border-color, color;
    
    &::before {
        @apply w-4 h-4 border rounded shadow-none bg-center bg-no-repeat;
        @apply duration-200 ease-in-out;
        content: "";
        background-size: 0px 0px;
        background-image: url('data:image/svg+xml;base64,PHN2ZyB4bWxucz0iaHR0cDovL3d3dy53My5vcmcvMjAwMC9zdmciIHdpZHRoPSIyNCIgaGVpZ2h0PSIyNCIgdmlld0JveD0iMCAwIDI0IDI0IiBmaWxsPSJub25lIiBzdHJva2U9IiNmZmZmZmYiIHN0cm9rZS13aWR0aD0iMiIgc3Ryb2tlLWxpbmVjYXA9InJvdW5kIiBzdHJva2UtbGluZWpvaW49InJvdW5kIiBjbGFzcz0ibHVjaWRlIGx1Y2lkZS1jaGVjayI+PHBhdGggZD0iTTIwIDYgOSAxN2wtNS01Ii8+PC9zdmc+');
        transition-property: background-color, background-size, border-color, color;
    }
}

.checkbox-input:checked ~ .checkbox-label {
    &::before {
        background-size: 12px 12px;
    }
}

.checkbox-input {
    &:not(:disabled) ~ .checkbox-label {
        @apply cursor-pointer;
    }
    &:disabled ~ .checkbox-label {
        @apply cursor-not-allowed;
    }

    & ~ .checkbox-label {
        @apply text-gray-800 dark:text-gray-400;
    }
    &:disabled ~ .checkbox-label {
        @apply text-gray-400 dark:text-gray-600;
    }

    & ~ .checkbox-label::before {
        @apply border-gray-300 bg-white;
        @apply dark:border-gray-600 dark:bg-gray-900;
    }
    &:not(:disabled):checked ~ .checkbox-label::before {
        @apply border-primary-600 bg-primary-600;
    }
    &:disabled ~ .checkbox-label::before {
        @apply border-gray-400 bg-gray-200;
    }
    &:disabled:checked ~ .checkbox-label::before {
        @apply dark:border-primary-400 dark:bg-primary-400;
    }
}
.field-checkbox:hover .checkbox-input {
    &:not(:disabled) ~ .checkbox-label::before {
        @apply border-primary-400 dark:border-primary-600;
    }

    &:not(:disabled):checked ~ .checkbox-label::before {
        @apply border-primary-800 dark:border-primary-500;
    }
}

.field-checkbox.is-invalid .checkbox-input {
    &:not(:disabled) ~ .checkbox-label::before {
        @apply border-danger-700 bg-danger-50;
    }
}
</style>
